import { NextRequest, NextResponse } from "next/server";
import { createServerSupabaseClient, createServiceRoleClient } from "@/lib/supabase/server";
import { generatePodcastScript, generateEpisodeAudio } from "@/lib/openai";
import { concatenateAudioBuffers, writeID3Tags } from "@/lib/audio";
import { uploadToR2 } from "@/lib/r2";
import type { GenerateRequest } from "@/types";

export const maxDuration = 300; // 5 minutes for edge function

export async function POST(request: NextRequest) {
  try {
    const supabase = createServerSupabaseClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body: GenerateRequest = await request.json();
    const { title, format, hostConfig, qualitySettings, documentIds } = body;

    if (!title || !format || !hostConfig || !documentIds?.length) {
      return NextResponse.json(
        { error: "title, format, hostConfig, and documentIds are required" },
        { status: 400 }
      );
    }

    // Create the episode
    const { data: episode, error: epError } = await supabase
      .from("episodes")
      .insert({
        user_id: user.id,
        series_id: body.seriesId || null,
        title,
        description: body.description || null,
        format,
        status: "processing",
        host_config: hostConfig,
        quality_settings: qualitySettings || {
          sampleRate: 44100,
          bitrate: 128,
          format: "mp3",
          speed: 1.0,
          normalizeVolume: true,
        },
      })
      .select()
      .single();

    if (epError || !episode) {
      return NextResponse.json(
        { error: epError?.message || "Failed to create episode" },
        { status: 500 }
      );
    }

    // Start async generation
    generateAsync(episode.id, user.id, documentIds, title, format, hostConfig, qualitySettings);

    return NextResponse.json({
      episodeId: episode.id,
      status: "processing",
      estimatedTime: documentIds.length * 60,
    });
  } catch (err: any) {
    console.error("Generate error:", err);
    return NextResponse.json(
      { error: err.message || "Generation failed" },
      { status: 500 }
    );
  }
}

async function generateAsync(
  episodeId: string,
  userId: string,
  documentIds: string[],
  title: string,
  format: any,
  hostConfig: any,
  qualitySettings: any
) {
  const supabase = createServiceRoleClient();

  try {
    // Fetch document contents
    const { data: documents } = await supabase
      .from("documents")
      .select("content_text")
      .in("id", documentIds);

    const contents = (documents || [])
      .map((d) => d.content_text)
      .filter(Boolean) as string[];

    if (contents.length === 0) {
      throw new Error("No document content found");
    }

    // Update status to generating
    await supabase
      .from("episodes")
      .update({ status: "generating" })
      .eq("id", episodeId);

    const startTime = Date.now();

    // Generate script
    const script = await generatePodcastScript(contents, format, hostConfig, title);

    // Generate audio
    const speed = qualitySettings?.speed || 1.0;
    const { audioBuffers, segments, chapters } = await generateEpisodeAudio(
      script,
      hostConfig,
      speed
    );

    // Combine audio
    const combinedAudio = concatenateAudioBuffers(audioBuffers);

    // Add ID3 tags
    const taggedAudio = writeID3Tags(combinedAudio, {
      title,
      artist: `${hostConfig.host1.name} & ${hostConfig.host2.name}`,
      album: "PodCraft",
      year: new Date().getFullYear(),
      genre: "Podcast",
      comment: `Generated by PodCraft`,
      trackNumber: 1,
    });

    // Upload to R2
    const audioKey = `episodes/${userId}/${episodeId}/audio.mp3`;
    const audioUrl = await uploadToR2(audioKey, taggedAudio, "audio/mpeg");

    const generationTime = (Date.now() - startTime) / 1000;

    // Update episode with results
    await supabase
      .from("episodes")
      .update({
        status: "ready",
        audio_url: audioUrl,
        audio_duration: segments.length > 0 ? segments[segments.length - 1].endTime : 0,
        audio_size: taggedAudio.length,
        transcript: segments as any,
        chapters: chapters as any,
        metadata: {
          generationTime,
          modelUsed: "gpt-4-turbo-preview",
          documentCount: contents.length,
          totalWords: contents.join(" ").split(/\s+/).length,
          tags: [],
        } as any,
      })
      .eq("id", episodeId);
  } catch (err: any) {
    console.error("Async generation failed:", err);
    await supabase
      .from("episodes")
      .update({
        status: "failed",
        metadata: { error: err.message } as any,
      })
      .eq("id", episodeId);
  }
}
